apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-logger
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-logger
  template:
    metadata:
      labels:
        app: sample-logger
    spec:
      containers:
        - name: logger
          image: busybox
          command: ["/bin/sh","-c","while true; do echo '{\"ts\":\"'$(date -Iseconds)'\", \"msg\": \"hello from sample logger\"}'; sleep 2; done"]
