apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  resources:
  - group: ""
    resources: ["pods", "secrets", "serviceaccounts"]
- level: RequestResponse
  resources:
  - group: ""
    resources: ["pods/exec", "pods/attach"]
  verbs: ["create","update","patch"]
- level: Metadata
  verbs: ["get","list","watch"]

# Note: configure the kube-apiserver to use this policy and ship logs to OTel/ELK for analysis
