apiVersion: v1
kind: Service
metadata:
  name: alert-exporter
  namespace: ml
spec:
  selector:
    app: alert-exporter
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-exporter
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-exporter
  template:
    metadata:
      labels:
        app: alert-exporter
    spec:
      containers:
        - name: alert-exporter
          image: alert-exporter:v1
          ports:
            - containerPort: 8000
          env:
            - name: WINDOWS_DIR
              value: /data/graphs
            - name: PROCESSED_DIR
              value: /data/processed
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: graphs-pvc
